### ISSUE TITLE
Inclusion in F-Droid

### ISSUE THREAD

**Issue by Poussinou** [AhiruSoftwareCompany/alcoholtestapp#60]
Hi,

Since this app is MIT licensed, are you considering the fact to add it to [F-Droid](https://f-droid.org/)? There is a strong community behind.

You can find some documentation [here](https://f-droid.org/docs/).

Otherwise, if you don't want to work on the inclusion of this app by yourself, would it be ok for you if someone else do it for you?

**Comment by dieechtenilente** [comment]
Hi,

until I see this app as a finished project I don't plan to release it anywhere but here. There are plans to release it as freeware on the Google PlayStore later this year. F-Droid looks interesting and I will publish my app there, too.
